CONFIG_GPIO=y
CONFIG_LOG=y
#CONFIG_BLINK_SLEEP_TIME_2000MS=y #this assignment is okay as it only turns on/off the 2000/250/1000 ms delay feature which
                                # is already coded in the choice in Kconfig but as the user prompt is hidden, the following
                                #assignment gives an error when we try to build it
#CONFIG_BLINK_SLEEP_TIME_MS=1000 # error: BLINK_SLEEP_TIME_MS (defined at C:/ncsfund/zephyr-course/app/Kconfig:29) is assigned in a
                                #configuration file, but is not directly user-configurable (has no prompt). It gets its value
                                #indirectly from other symbols.
#CONFIG_APP_HEARTBEAT_PERIOD_MS=600                               