#CONFIG_CPP=y
#CONFIG_REQUIRES_FULL_LIBCPP=y
#CONFIG_GPIO=y
#CONFIG_CONSOLE=y
CONFIG_USB_DEVICE_STACK=y
#CONFIG_LOG=y
#CONFIG_PRINTK=y
#CONFIG_BOARD_EARLY_INIT_HOOK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
#CONFIG_UART_CONSOLE=y
#CONFIG_SERIAL=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y
#CONFIG_BOOT_DELAY=2000