CONFIG_GPIO=y
# CONFIG_SENSOR=y   // no longer used — replaced by custom l6driver API
CONFIG_L6_DRIVER=y
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
#CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_BOOT_DELAY=2000