CONFIG_GPIO=y
CONFIG_SENSOR=y   
CONFIG_L6_DRIVER=y
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y #attaches the shell to whatever device is set as zephyr,console in your overlay — 
                            #so if you already have USB CDC-ACM as the console, the shell appears on that same COM port automatically.
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y #turns the USB port into a virtual serial port without extra wires for UART. but its not actually UART.
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_BOOT_DELAY=2000